import { RollMaster } from "@/types/roll-master";

export let mockRolls: RollMaster[] = [
    {
        id: "1",
        itemType: "Film",
        itemCode: "RF12345", // RF + Random
        itemName: "BOPP Gloss Film 12mic",
        supplierItemCode: "SUP-BOPP-12",
        mill: "Reliance Industries",
        quality: "Premium",
        rollWidthMM: 600,
        thicknessMicron: 12,
        density: 0.9,
        faceGSM: 18,
        releaseGSM: 0,
        adhesiveGSM: 0,
        totalGSM: 18,
        shelfLifeDays: 365,
        purchaseUnit: "KG",
        stockUnit: "KG",
        purchaseRate: 150,
        hsnCode: "3920",
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01"),
    },
    {
        id: "r-flm002",
        itemType: "Film",
        itemCode: "RF67890",
        itemName: "Met Pet Silver 12mic 800mm",
        supplierItemCode: "SUP-MET-12-800",
        mill: "Jindal",
        quality: "Standard",
        rollWidthMM: 800,
        thicknessMicron: 12,
        density: 1.4,
        faceGSM: 20,
        totalGSM: 20,
        purchaseUnit: "KG",
        stockUnit: "KG",
        purchaseRate: 200,
        hsnCode: "3920",
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01"),
    },
    {
        id: "r-flm003",
        itemType: "Film",
        itemCode: "RF54321",
        itemName: "Met Pet Gold 12mic 525mm",
        supplierItemCode: "SUP-MET-12-525",
        mill: "Cosmo",
        quality: "Standard",
        rollWidthMM: 525,
        thicknessMicron: 12,
        density: 1.4,
        faceGSM: 20,
        totalGSM: 20,
        purchaseUnit: "KG",
        stockUnit: "KG",
        purchaseRate: 210,
        hsnCode: "3920",
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01"),
    },
    {
        id: "2",
        itemType: "Paper",
        itemCode: "RP98765", // RP + Random
        itemName: "Kraft Paper 80 GSM",
        supplierItemCode: "SUP-KP-80",
        mill: "Mill A",
        quality: "Standard",
        rollWidthMM: 900,
        thicknessMicron: 100,
        density: 0.8,
        faceGSM: 80,
        releaseGSM: 0,
        adhesiveGSM: 0,
        totalGSM: 80,
        shelfLifeDays: 730,
        purchaseUnit: "KG",
        stockUnit: "KG",
        purchaseRate: 65,
        hsnCode: "4811",
        createdAt: new Date("2025-01-05"),
        updatedAt: new Date("2025-01-05"),
    },
];
