"use client";

import { useState } from "react";
import { format } from "date-fns";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { MotherRollDialog } from "./mother-roll-dialog";
import { ChildRollTable, ChildRollEntry } from "./child-roll-table";
import { toast } from "sonner";
import { Save } from "lucide-react";
import { StockItem } from "@/types/stock-master";
import { slittingStorage } from "@/services/storage/slitting-storage";
import { SlittingJob, SlittingOutputRoll, SlittingInputRoll } from "@/types/jumbo-slitting";

export function SlittingForm() {
    const [selectedMotherRoll, setSelectedMotherRoll] = useState<StockItem | null>(null);
    const [childEntries, setChildEntries] = useState<ChildRollEntry[]>([]);
    const [dialogOpen, setDialogOpen] = useState(false);

    // Additional Fields
    const [machineName, setMachineName] = useState("");
    const [operatorName, setOperatorName] = useState("");
    const [wastageKg, setWastageKg] = useState<number>(0);

    // Auto-generated fields
    const todayDate = format(new Date(), "dd-MMM-yyyy");
    // Note: Slitting No is generated by storage on save (SL00001/...)
    // We can show "Auto-Generated" here.

    const handleMotherRollSelect = (roll: StockItem) => {
        setSelectedMotherRoll(roll);
        // Reset child selection when mother roll changes
        setChildEntries([]);
        setWastageKg(0);
    };

    const handleSave = () => {
        if (!selectedMotherRoll) {
            toast.error("Please select a Mother Roll.");
            return;
        }

        if (childEntries.length === 0 || childEntries.every(e => e.qtyMtr === 0 && e.qtyKg === 0)) {
            toast.error("Please enter output quantities.");
            return;
        }

        if (!machineName) {
            toast.error("Please select a Machine.");
            return;
        }

        try {
            // Prepare Data for Storage

            // 1. Input Roll Data
            const inputRoll: SlittingInputRoll = {
                grnItemId: selectedMotherRoll.id, // Stock Item ID
                grnId: "STOCK", // Since it exists in stock
                rollMasterId: selectedMotherRoll.itemCode || "UNKNOWN", // Fallback
                itemCode: selectedMotherRoll.itemCode,
                itemName: selectedMotherRoll.itemName,
                batchNo: selectedMotherRoll.batchNo || "BATCH-NA",

                inputWidth: selectedMotherRoll.widthMM || 0,
                inputGSM: selectedMotherRoll.gsm || 0,
                inputRM: selectedMotherRoll.runningMtr || 0,
                inputSqMtr: selectedMotherRoll.sqMtr || 0,
                inputKg: selectedMotherRoll.quantity || 0, // In Stock, quantity usually is weight? or check uom

                itemType: selectedMotherRoll.category, // 'Roll' is category but we might need 'Film'/'Paper' type. 
                // StockItem doesn't stricly have 'type'. RollMaster does. 
                // We'll pass generic 'Roll' or attempt to infer.

                uom: selectedMotherRoll.uom,

                // Process Consumption logic:
                // User enters output Mtr/Kg. We calculate how much Input was consumed.
                // Usually it matches total output + wastage?
                // Or if we run 1000m, we consume 1000m linear length.

                // Let's assume Process Length = Max(Child Output Length)
                inputProcessRM: Math.max(...childEntries.map(e => e.qtyMtr)),
            };

            // 2. Output Rolls
            // Expand entries: If 5 rolls of X, we create 5 entries? 
            // The storage expects array of `SlittingOutputRoll`.
            // Yes, user said "no of roll add krunga". So if qtyRolls=5, we create 5 distinct QR codes/items.

            const outputRolls: SlittingOutputRoll[] = [];

            childEntries.forEach(entry => {
                if (entry.qtyRolls > 0) {
                    const weightPerRoll = entry.qtyKg / entry.qtyRolls; // Avg weight
                    const lengthPerRoll = entry.qtyMtr; // Usually length is same for all if parallel? 
                    // Or did user mean Total Mtr? "qty (mtr)... no of roll"
                    // Usually "qty mtr" means "Length per Roll". 
                    // Let's assume Length Per Roll.

                    for (let i = 0; i < entry.qtyRolls; i++) {
                        outputRolls.push({
                            rollMasterId: entry.masterId,
                            outputWidth: entry.width,
                            outputGSM: selectedMotherRoll.gsm || 0, // Inherit

                            outputRM: entry.qtyMtr,
                            outputKg: weightPerRoll,
                            outputSqMtr: (entry.qtyMtr * entry.width) / 1000,

                            itemCode: entry.itemCode,
                            itemName: entry.itemName,
                            batchNo: "", // Generated by storage
                            itemType: selectedMotherRoll.category, // Propagate
                        });
                    }
                }
            });

            const jobData = {
                slittingDate: new Date().toISOString(),
                inputRoll,
                outputRolls,
                wastageKg: wastageKg,
                machineNo: machineName,
                operatorName,
                status: 'Completed' as const
            };

            const savedJob = slittingStorage.save(jobData);

            toast.success(`Slitting Entry Saved! Voucher No: ${savedJob.id}`);

            // Reset Form on Success
            setSelectedMotherRoll(null);
            setChildEntries([]);
            setWastageKg(0);
            setMachineName("");

        } catch (e) {
            console.error(e);
            toast.error("Failed to save slitting entry.");
        }
    };

    // Calculation Displays
    const remainingMtr = selectedMotherRoll
        ? (selectedMotherRoll.runningMtr || 0) - Math.max(0, ...childEntries.map(e => e.qtyMtr))
        : 0;

    return (
        <div className="space-y-4">
            {/* Main Header Card: Combined Slitting Details & Material Selection */}
            <Card className="rounded-md shadow-sm border-blue-100/50">
                <CardHeader className="py-2 px-4 bg-muted/20 border-b flex flex-row items-center justify-between">
                    <CardTitle className="text-sm font-bold text-blue-700">Slitting Operation</CardTitle>
                    <div className="flex items-center gap-2">
                        <span className="text-[10px] text-muted-foreground font-mono">
                            {todayDate}
                        </span>
                    </div>
                </CardHeader>
                <CardContent className="p-3">
                    <div className="flex flex-col md:flex-row gap-4 items-start">

                        {/* LEFT: BASIC INPUTS (Compact Grid) */}
                        <div className="grid grid-cols-2 gap-2 w-full md:w-[45%] shrink-0">
                            <div className="space-y-0.5">
                                <Label className="text-[10px] uppercase font-bold text-muted-foreground">Machine</Label>
                                <Select value={machineName} onValueChange={setMachineName}>
                                    <SelectTrigger className="h-7 text-xs bg-white">
                                        <SelectValue placeholder="Select Machine" />
                                    </SelectTrigger>
                                    <SelectContent>
                                        <SelectItem value="Slitter-01">Slitter Machine 01</SelectItem>
                                        <SelectItem value="Slitter-02">Slitter Machine 02</SelectItem>
                                        <SelectItem value="Rewinder-01">Rewinder 01</SelectItem>
                                    </SelectContent>
                                </Select>
                            </div>
                            <div className="space-y-0.5">
                                <Label className="text-[10px] uppercase font-bold text-muted-foreground">Operator</Label>
                                <Input
                                    value={operatorName}
                                    onChange={e => setOperatorName(e.target.value)}
                                    placeholder="Name"
                                    className="h-7 text-xs bg-white"
                                />
                            </div>
                            <div className="space-y-0.5">
                                <Label className="text-[10px] uppercase font-bold text-muted-foreground">Slitting No</Label>
                                <Input value="Auto-Generated" disabled className="h-7 bg-muted/50 font-mono text-[10px] text-muted-foreground" />
                            </div>
                            <div className="space-y-0.5">
                                <Label className="text-[10px] uppercase font-bold text-muted-foreground">Wastage (Kg)</Label>
                                <Input
                                    type="number"
                                    value={wastageKg}
                                    onChange={e => setWastageKg(parseFloat(e.target.value) || 0)}
                                    className="h-7 text-xs bg-white text-right font-medium text-amber-700 border-amber-200 focus-visible:ring-amber-400"
                                    placeholder="0.00"
                                />
                            </div>
                        </div>

                        {/* SEPARATOR */}
                        <div className="hidden md:block w-px bg-border self-stretch mx-2"></div>

                        {/* RIGHT: MOTHER ROLL SELECTION */}
                        <div className="flex-1 w-full space-y-2">
                            <div className="flex justify-between items-center mb-1">
                                <Label className="text-[10px] uppercase font-bold text-muted-foreground">Mother Roll Material</Label>
                                <Button onClick={() => setDialogOpen(true)} variant="outline" size="sm" className="h-6 text-[10px] border-blue-200 text-blue-700 hover:bg-blue-50">
                                    {selectedMotherRoll ? "Change Roll" : "Select Roll"}
                                </Button>
                            </div>

                            {selectedMotherRoll ? (
                                <div className="bg-blue-50/50 rounded border border-blue-100 p-2 text-xs">
                                    <div className="font-bold text-blue-900 leading-tight">
                                        {selectedMotherRoll.itemName} <span className="opacity-70 font-normal">({selectedMotherRoll.itemCode})</span>
                                    </div>
                                    <div className="flex flex-wrap gap-x-3 gap-y-1 mt-1 text-[11px] text-muted-foreground font-mono items-center">
                                        <span><span className="font-semibold text-gray-600">Specs:</span> {selectedMotherRoll.widthMM}mm | {selectedMotherRoll.gsm}GSM</span>
                                        <span className="text-gray-300">|</span>
                                        <span><span className="font-semibold text-gray-600">Stock:</span> {selectedMotherRoll.runningMtr?.toLocaleString()}m / {selectedMotherRoll.quantity?.toFixed(2)}kg</span>
                                        <span className="text-gray-300">|</span>
                                        <span className={remainingMtr < 0 ? "text-red-600 font-bold bg-white px-1 rounded shadow-sm" : "text-green-700 font-bold bg-white px-1 rounded shadow-sm"}>
                                            Rem: {remainingMtr.toLocaleString()}m
                                        </span>
                                    </div>
                                </div>
                            ) : (
                                <div onClick={() => setDialogOpen(true)} className="h-[52px] border-2 border-dashed border-gray-200 rounded flex items-center justify-center text-xs text-muted-foreground cursor-pointer hover:bg-gray-50 hover:border-gray-300 transition-colors">
                                    Click to Select Mother Roll
                                </div>
                            )}
                        </div>

                    </div>
                </CardContent>
            </Card>

            {/* CHILD ROLL SECTION */}
            {selectedMotherRoll && (
                <Card className="shadow-sm border-t-2 border-t-blue-600">
                    <CardContent className="p-0">
                        <div className="p-2">
                            <ChildRollTable
                                motherRoll={selectedMotherRoll}
                                entries={childEntries}
                                onEntriesChange={setChildEntries}
                            />
                        </div>
                        <div className="p-3 border-t bg-muted/5 flex justify-end">
                            <Button onClick={handleSave} size="sm" className="w-[180px] bg-green-600 hover:bg-green-700 h-8 text-xs font-bold shadow-sm">
                                <Save className="mr-2 h-3.5 w-3.5" /> Save Slitting Entry
                            </Button>
                        </div>
                    </CardContent>
                </Card>
            )}

            <MotherRollDialog
                open={dialogOpen}
                onOpenChange={setDialogOpen}
                onSelect={handleMotherRollSelect}
            />
        </div>
    );
}
