"use client";

import { useState, useEffect } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { toast } from "sonner";
import { RefreshCw, Check, Palette, Hexagon, Moon, Sun, Sparkles } from "lucide-react";
import { useTheme } from "@/hooks/useTheme";
import { CustomThemeColors } from "@/lib/theme/types";
import { applyCustomTheme, generateColorVariants } from "@/lib/theme/utils";
import { ThemePreview } from "@/components/theme/theme-preview";
import { motion } from "framer-motion";

const THEME_PRESETS = [
    { name: "Default", start: "#0f172a", end: "#334155", class: "from-slate-900 to-slate-700" },
    { name: "Milan Sky", start: "#06b6d4", end: "#2563eb", class: "from-cyan-500 to-blue-600" },
    { name: "Sunset", start: "#ea580c", end: "#dc2626", class: "from-orange-600 to-red-600" },
    { name: "Forest", start: "#10b981", end: "#059669", class: "from-emerald-500 to-emerald-600" },
    { name: "Royal", start: "#8b5cf6", end: "#7c3aed", class: "from-violet-500 to-violet-600" },
    { name: "Midnight", start: "#000000", end: "#1e293b", class: "from-black to-slate-800" },
];

export default function SettingsPage() {
    const { customTheme, setCustomTheme, theme, removeCustomTheme, setMode, isDark } = useTheme();

    // Initialize state
    const [startColor, setStartColor] = useState("#06b6d4");
    const [endColor, setEndColor] = useState("#2563eb");
    const [themeName, setThemeName] = useState("");
    const [isLoading, setIsLoading] = useState(false);

    // Sync with global theme on mount
    useEffect(() => {
        if (theme.variant === 'custom' && customTheme) {
            setStartColor(customTheme.gradientStart || customTheme.primary || "#06b6d4");
            setEndColor(customTheme.gradientEnd || "#2563eb");
            setThemeName(customTheme.name || "");
        }
    }, [theme, customTheme]);

    const handleApplyTheme = async (start: string, end: string, name?: string) => {
        setIsLoading(true);
        try {
            // Auto-generate full palette from the start color just to be safe/consistent
            // OR use the provided end color if it was manually tweaked or from preset.
            // Since we are in "AI Mode" for custom, let's recalculate if it's a custom apply?
            // Actually, if coming from Preset, we want specific colors.
            // If coming from Custom, we might want to ensure tertiary is set.

            let colors: CustomThemeColors;

            // Heuristic: If name is in presets, use start/end exactly.
            // If custom, generate full palette.
            const isPreset = THEME_PRESETS.some(p => p.name === name);

            if (isPreset) {
                colors = {
                    primary: start,
                    gradientStart: start,
                    gradientEnd: end
                    // tertiary: will be auto-generated by utils if missing, or we can leave undefined
                };
            } else {
                // Custom / AI Generation
                colors = generateColorVariants(start);
                // Ensure the "end" color in state matches if we want (or we trust the generator)
                // For this implementation, let's use the generator's output for consistency
            }

            // 1. Force Apply immediately
            const tempTheme = {
                ...colors,
                name: name || "Custom Theme",
                id: "temp",
                createdAt: new Date(),
                updatedAt: new Date()
            };
            applyCustomTheme(tempTheme);

            // 2. Persist State
            await setCustomTheme(colors, name || "Custom Theme");

            setStartColor(colors.primary);
            setEndColor(colors.gradientEnd || end); // Update state to match reality

            toast.success("Theme updated successfully!");
        } catch (error) {
            console.error(error);
            toast.error("Failed to update theme");
        } finally {
            setTimeout(() => setIsLoading(false), 500);
        }
    };

    const handleReset = async () => {
        setIsLoading(true);
        try {
            await removeCustomTheme();
            setStartColor("#06b6d4");
            setEndColor("#2563eb");
            setThemeName("");
            toast.success("Theme reset to default");
        } catch (e) {
            toast.error("Failed to reset theme");
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="flex flex-col lg:flex-row h-full bg-slate-50/50 p-4 gap-4 max-w-[1600px] mx-auto font-sans">
            {/* Left Column: Controls */}
            <motion.div
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                className="w-full lg:w-[400px] flex flex-col gap-4"
            >
                <Card className="border-0 shadow-xl bg-white/90 backdrop-blur-xl overflow-hidden">
                    <CardHeader className="pb-3 pt-4 px-4 bg-slate-50/50 border-b border-slate-100/50">
                        <div className="flex items-center justify-between">
                            <div className="space-y-0.5">
                                <CardTitle className="text-base font-bold flex items-center gap-2">
                                    <Palette className="h-4 w-4 text-blue-600" />
                                    Theme Customizer
                                </CardTitle>
                                <CardDescription className="text-xs">
                                    Control app appearance
                                </CardDescription>
                            </div>
                            <div className="flex items-center gap-1.5 bg-white rounded-full px-2 py-1 shadow-sm border border-slate-100">
                                <Sun className="h-3 w-3 text-amber-500" />
                                <Switch
                                    checked={isDark}
                                    onCheckedChange={(c) => setMode(c ? 'dark' : 'light')}
                                    className="scale-75 origin-center"
                                />
                                <Moon className="h-3 w-3 text-slate-700" />
                            </div>
                        </div>
                    </CardHeader>
                    <CardContent className="space-y-4 p-4">

                        {/* Presets */}
                        <div className="space-y-2">
                            <Label className="text-[10px] font-bold uppercase text-slate-500 tracking-wider flex items-center justify-between">
                                Pro Presets
                            </Label>
                            <div className="grid grid-cols-3 gap-2">
                                {THEME_PRESETS.map((preset) => (
                                    <button
                                        key={preset.name}
                                        onClick={() => {
                                            setStartColor(preset.start);
                                            setEndColor(preset.end);
                                            handleApplyTheme(preset.start, preset.end, preset.name);
                                        }}
                                        className="group relative flex flex-col items-center gap-1.5 p-2 rounded-lg border border-slate-100 bg-white shadow-sm hover:shadow-md hover:border-blue-100 transition-all active:scale-[0.98]"
                                    >
                                        <div className="flex w-full h-5 rounded overflow-hidden ring-1 ring-slate-100">
                                            <div style={{ background: preset.start }} className="flex-1" />
                                            <div style={{ background: preset.end }} className="flex-1" />
                                            <div className="flex-1 bg-slate-100/50" />
                                        </div>
                                        <span className="text-[10px] font-medium text-slate-600 group-hover:text-blue-600 transition-colors truncate w-full text-center">
                                            {preset.name}
                                        </span>
                                    </button>
                                ))}
                            </div>
                        </div>

                        {/* Custom Section - Single Color AI Generation */}
                        <div className="space-y-3 pt-3 border-t border-slate-100">
                            <Label className="text-[10px] font-bold uppercase text-slate-500 tracking-wider flex items-center gap-2">
                                <Sparkles className="h-3 w-3 text-purple-500" />
                                AI Brand Theme
                            </Label>

                            <div className="space-y-3">
                                <div className="space-y-1.5">
                                    <Label className="text-[10px] text-slate-500">Brand Name</Label>
                                    <Input
                                        placeholder="e.g. My Brand"
                                        value={themeName}
                                        onChange={(e) => setThemeName(e.target.value)}
                                        className="h-8 text-xs bg-slate-50 border-slate-200"
                                    />
                                </div>

                                <div className="space-y-1.5">
                                    <Label className="text-[10px] text-slate-500">Primary Brand Color</Label>
                                    <div className="flex gap-2">
                                        <div className="relative h-9 w-full rounded-md border border-slate-200 overflow-hidden shadow-sm flex items-center gap-2 px-2 bg-white">
                                            <div className="relative h-5 w-5 rounded-full overflow-hidden border border-slate-200 shadow-sm shrink-0">
                                                <input
                                                    type="color"
                                                    value={startColor} // Using startColor as main brand color state
                                                    onChange={(e) => {
                                                        const newColor = e.target.value;
                                                        setStartColor(newColor);
                                                        // Auto-generate internal state for preview?
                                                        const variants = generateColorVariants(newColor);
                                                        setEndColor(variants.gradientEnd || newColor);
                                                    }}
                                                    className="absolute -top-4 -left-4 w-[200%] h-[200%] cursor-pointer"
                                                />
                                            </div>
                                            <Input
                                                value={startColor}
                                                onChange={(e) => {
                                                    setStartColor(e.target.value);
                                                    if (e.target.value.length === 7) {
                                                        const variants = generateColorVariants(e.target.value);
                                                        setEndColor(variants.gradientEnd || e.target.value);
                                                    }
                                                }}
                                                className="h-6 text-xs uppercase font-mono text-slate-600 border-0 focus-visible:ring-0 p-0"
                                                maxLength={7}
                                            />
                                        </div>
                                    </div>
                                    <p className="text-[10px] text-slate-400">
                                        We automatically generate secondary gradients and table header colors from this base.
                                    </p>
                                </div>

                                {/* Visualizing the generated palette (Read Only) */}
                                <div className="grid grid-cols-3 gap-2 pt-1">
                                    <div className="h-6 rounded bg-slate-100 flex items-center justify-center text-[8px] text-slate-400 border border-slate-200" style={{ background: startColor, color: '#fff' }}>Primary</div>
                                    <div className="h-6 rounded bg-slate-100 flex items-center justify-center text-[8px] text-slate-400 border border-slate-200" style={{ background: endColor, color: '#fff' }}>Gradient</div>
                                    <div className="h-6 rounded bg-slate-100 flex items-center justify-center text-[8px] text-slate-500 border border-slate-200" style={{ background: generateColorVariants(startColor).tertiary }}>Headers</div>
                                </div>
                            </div>
                        </div>

                        {/* Actions */}
                        <div className="flex flex-col gap-2 pt-1">
                            <Button
                                className="w-full bg-slate-900 text-white hover:bg-slate-800 h-9 text-xs font-medium shadow-lg shadow-slate-900/10"
                                onClick={() => handleApplyTheme(startColor, endColor, themeName)}
                                disabled={isLoading}
                            >
                                {isLoading ? (
                                    <RefreshCw className="mr-2 h-3 w-3 animate-spin" />
                                ) : (
                                    <Check className="mr-2 h-3 w-3" />
                                )}
                                Apply Theme
                            </Button>
                            <Button
                                variant="outline"
                                className="w-full h-8 text-[10px] border-slate-200 text-slate-500 hover:text-red-600 hover:border-red-100 hover:bg-red-50"
                                onClick={handleReset}
                                disabled={isLoading}
                            >
                                Reset Defaults
                            </Button>
                        </div>
                    </CardContent>
                </Card>
            </motion.div>

            {/* Right Column: Preview */}
            <motion.div
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.1 }}
                className="flex-1 flex flex-col gap-4"
            >
                <div className="sticky top-4 space-y-3">
                    <Card className="border-0 shadow-2xl overflow-hidden bg-white p-1 ring-1 ring-slate-900/5">
                        <ThemePreview startColor={startColor} endColor={endColor} />
                    </Card>

                    <div className="flex items-center gap-3 p-3 rounded-lg bg-gradient-to-br from-blue-50 to-indigo-50 border border-blue-100 shadow-sm">
                        <div className="p-1.5 bg-white rounded-md shadow-sm text-blue-600">
                            <Hexagon className="h-4 w-4" />
                        </div>
                        <div className="space-y-0.5">
                            <p className="text-xs font-semibold text-blue-900">Live Brand Preview</p>
                            <p className="text-[10px] text-blue-700/80">
                                Real-time verification of contrast and aesthetic.
                            </p>
                        </div>
                    </div>
                </div>
            </motion.div>
        </div>
    );
}
